name: CI build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 3
    env:
      TERM: xterm
      AM_COLOR_TESTS: always

    steps:
    - uses: actions/checkout@v4
    - name: Show OS info
      run: cat /etc/os-release
    - name: Install dependencies
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libhamlib-dev libxmlrpc-core-c3-dev libglib2.0-dev libcmocka-dev python3-pexpect python3-dev astyle
    - name: Set up datadir
      run: mkdir datadir && ln -s $PWD/share datadir/tlf
    - name: Check source formatting
      run: |
        F=$(astyle --dry-run --formatted --options=tools/astylerc src/*.[ch])
        if [ ! -z "$F" ] ; then sed -e 's/^F/To be f/' <<< $F; exit 1; fi
    - name: Autoreconf and basic make
      run: |
        autoreconf -i && ./configure --datadir=$PWD/datadir && make -j2
    - name: Configure with xmlrpc
      run: |
        make clean && ./configure --datadir=$PWD/datadir --enable-fldigi-xmlrpc && make -j2
    - name: Configure with xmlrpc and Python plugin
      run: |
        make clean && ./configure --datadir=$PWD/datadir --enable-fldigi-xmlrpc --enable-python-plugin && make -j2
    - name: Run tests
      id: run_tests
      continue-on-error: true
      run: make check
    - name: Show failed test results
      if: ${{ steps.run_tests.outcome == 'failure' }}
      run: |
        for f in test/run_*.log; do
            grep -q FAILED $f && echo -e "\n>>> $f:\n" && cat $f
        done
        exit 1
